apiVersion: kubeflow.org/v1
kind: TFJob
metadata:
  name: job1
spec:
  max-instances: 4
  min-instances: 1
  cleanPodPolicy: "All"
  tfReplicaSpecs:
    PS:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          terminationGracePeriodSeconds: 0
          containers:
          - name: tensorflow
            image: tensorflow/tensorflow:1.15.0-py3
            command: ["/bin/sh","-c"]
            args: ["apt update && apt install -y libsm6 libxext6 libgl1-mesa-glx && apt-get install -y libxrender-dev && pip install opencv-python && curl -s https://raw.githubusercontent.com/Louis5499/ai-platform-exp-repo/master/alexnet-test-8.py | python3 -"]
            # command: ["pip install cv2 && ", "/bin/bash", "-c", "curl -s https://raw.githubusercontent.com/Louis5499/ai-platform-exp-repo/master/alexnet-test-8.py | python3 -"]
            ports:
            - containerPort: 2222
              name: tfjob-port
            # resources:
            #   limits:
            #     cpu: "4"
            #     memory: "8Gi"
    Worker:
      replicas: 4
      restartPolicy: OnFailure
      template:
        spec:
          terminationGracePeriodSeconds: 0
          containers:
          - name: tensorflow
            image: tensorflow/tensorflow:1.15.0-gpu-py3
            command: ["/bin/sh","-c"]
            args: ["apt update && apt install -y libsm6 libxext6 libgl1-mesa-glx && apt-get install -y libxrender-dev && pip install opencv-python && curl -s https://raw.githubusercontent.com/Louis5499/ai-platform-exp-repo/master/alexnet-test-8.py | python3 -"]
            env:
            - name: "global_steps"
              value: "100000"
            ports:
            - containerPort: 2222
              name: tfjob-port
            resources:
              limits:
                # cpu: "4"
                # memory: "8Gi"
                "nvidia.com/gpu": 1